import type { Merchant, SimMenu } from "./types.ts";

const cableMenu = (brand: string): SimMenu => ({
  prompt: `Thank you for calling ${brand}. For billing and payments, press 1. For technical support, press 2. To add or change services, press 3. To cancel or disconnect service, press 4. For all other questions, press 0.`,
  options: [
    { digit: "1", label: "billing", next: { prompt: "For your current balance, press 1. To speak with a billing representative about your bill, press 2.", options: [{ digit: "1", label: "balance" }, { digit: "2", label: "billing representative", next: "billing" }] } },
    { digit: "2", label: "technical support" },
    { digit: "3", label: "add or change services", next: "billing" },
    { digit: "4", label: "cancel or disconnect", next: "retention" },
    { digit: "0", label: "other", next: "billing" },
  ],
});

export const BUILTIN_MERCHANTS: Merchant[] = [
  {
    id: "xfinity",
    name: "Xfinity (Comcast)",
    category: "internet",
    phone: "+18009346489",
    hours: "24/7 for billing; retention 8am to 9pm local",
    verification: ["Account holder name", "Service address", "Last 4 of SSN or account PIN"],
    ivr: ["Say or press the option for cancel/disconnect to reach retention, which has the most room on price", "If asked to describe the issue, say 'cancel service'"],
    tactics: [
      "Ask the billing rep what promotions the account qualifies for before mentioning cancelling",
      "Name a specific competitor price at the same address (fiber or 5G home internet)",
      "Say you are ready to cancel today and ask to be transferred to the loyalty or retention department",
      "Ask for a 12 month promo with no contract, or decline equipment rental to cut the bill",
      "Before accepting, confirm the new monthly total with taxes and fees, the promo length and whether a contract applies",
    ],
    competitors: [
      { name: "T-Mobile 5G Home Internet", offer: "about $50 a month with AutoPay, no annual contract" },
      { name: "AT&T Fiber 300", offer: "about $55 a month for the first year" },
      { name: "Verizon 5G Home", offer: "about $50 to $60 a month with AutoPay" },
    ],
    cancel: "Call and ask for disconnect; return equipment within 30 days and keep the return receipt",
    written: { url: "https://www.xfinity.com/support/contact-us" },
    typicalWin: "$20 to $40 a month off for 12 months",
    sim: {
      menu: cableMenu("Xfinity"),
      holdSeconds: 14,
      repNames: ["Marcus", "Dana", "Keisha"],
      requires: ["last4"],
      offers: [
        { monthly: 95, months: 12, description: "$10 off for 12 months on your current plan", unlock: "ask" },
        { monthly: 75, months: 12, description: "Gigabit Connect promo at $75 for 12 months, no contract", unlock: "competitor" },
        { monthly: 60, months: 12, description: "loyalty rate of $60 a month for 12 months, no contract, equipment included", unlock: "loyalty" },
      ],
      saveAttempts: 2,
      refundRate: 1,
    },
  },
  {
    id: "spectrum",
    name: "Spectrum",
    category: "internet",
    phone: "+18557077328",
    hours: "24/7",
    verification: ["Account holder name", "Service address", "Account PIN"],
    ivr: ["Say 'cancel service' when asked why you are calling", "Retention is called the 'customer retention' team"],
    tactics: [
      "Spectrum rarely discounts for existing customers on billing; go straight to cancel to reach retention",
      "Mention a fiber or 5G competitor with a concrete price",
      "Ask to remove the WiFi equipment fee or add a new customer promo",
    ],
    competitors: [
      { name: "T-Mobile 5G Home Internet", offer: "about $50 a month with AutoPay" },
      { name: "AT&T Fiber 300", offer: "about $55 a month" },
    ],
    cancel: "Phone only; return equipment to a store or UPS",
    typicalWin: "$10 to $30 a month off for 12 months",
    sim: {
      menu: {
        prompt: "Welcome to Spectrum. In a few words, tell me what you're calling about. You can say things like 'pay my bill' or 'technical support'.",
        speech: true,
        options: [
          { digit: "1", label: "pay my bill" },
          { digit: "2", label: "billing question", next: "billing" },
          { digit: "3", label: "cancel service", next: "retention" },
        ],
      },
      holdSeconds: 18,
      repNames: ["Tyler", "Monique"],
      requires: ["pin"],
      offers: [
        { monthly: 70, months: 12, description: "Internet Premier promo at $70 for 12 months", unlock: "competitor" },
        { monthly: 55, months: 12, description: "retention rate of $55 a month for 12 months with the WiFi fee waived", unlock: "cancel" },
      ],
      saveAttempts: 2,
      refundRate: 1,
    },
  },
  {
    id: "att",
    name: "AT&T",
    category: "internet",
    phone: "+18002882020",
    hours: "7am to 10pm local",
    verification: ["Account holder name", "Passcode", "Billing ZIP"],
    ivr: ["Say 'cancel' to reach the loyalty team", "Have the account passcode ready, AT&T asks before anything else"],
    tactics: [
      "Ask the loyalty team about current retention credits for fiber",
      "Point to the price the same plan has for new customers",
      "Ask for a monthly bill credit if a plan change isn't possible",
    ],
    competitors: [
      { name: "Xfinity", offer: "about $40 to $55 a month new customer promos" },
      { name: "T-Mobile 5G Home Internet", offer: "about $50 a month" },
    ],
    cancel: "Call loyalty; return the gateway within 21 days",
    typicalWin: "$10 to $25 a month credit for 12 months",
    sim: {
      menu: cableMenu("AT&T"),
      holdSeconds: 10,
      repNames: ["Priya", "Jordan"],
      requires: ["pin"],
      offers: [
        { monthly: 70, months: 12, description: "a $10 monthly loyalty credit, so $70 a month for 12 months", unlock: "competitor" },
        { monthly: 60, months: 12, description: "a $20 monthly loyalty credit, so $60 a month for 12 months", unlock: "loyalty" },
      ],
      saveAttempts: 1,
      refundRate: 1,
    },
  },
  {
    id: "verizon",
    name: "Verizon Wireless",
    category: "wireless",
    phone: "+18009220204",
    hours: "7am to 9pm local",
    verification: ["Account PIN", "Account holder name"],
    ivr: ["Say 'cancel' or 'switch carriers' to reach the loyalty department"],
    tactics: [
      "Check for plan changes that drop perks you don't use",
      "Ask for loyalty discounts and promotional credits",
      "Mention a competitor port-in deal with numbers",
    ],
    competitors: [
      { name: "T-Mobile", offer: "port-in deals with a free line or device credits" },
      { name: "Visible or Mint", offer: "about $25 to $30 a line on the same network family" },
    ],
    cancel: "Port the number out to cancel; do not cancel first",
    typicalWin: "$10 to $25 a month in loyalty credits",
    sim: {
      menu: cableMenu("Verizon"),
      holdSeconds: 8,
      repNames: ["Alyssa", "Ben"],
      requires: ["pin"],
      offers: [
        { monthly: 75, months: 12, description: "move to Unlimited Welcome for $75 a month", unlock: "ask" },
        { monthly: 65, months: 12, description: "Unlimited Welcome with a $10 loyalty credit, so $65 a month for 12 months", unlock: "competitor" },
      ],
      saveAttempts: 1,
      refundRate: 1,
    },
  },
  {
    id: "tmobile",
    name: "T-Mobile",
    category: "wireless",
    phone: "+18009378997",
    hours: "24/7",
    verification: ["Account PIN", "Account holder name"],
    ivr: ["Dial 611 from the line or say 'cancel' to reach care"],
    tactics: ["Ask care for loyalty credits", "Ask to remove insurance or add-ons you don't use", "Ask about a newer plan with the same features for less"],
    competitors: [{ name: "Visible or Mint", offer: "about $25 to $30 a line" }],
    cancel: "Port the number out",
    typicalWin: "$5 to $20 a month",
    sim: {
      menu: cableMenu("T-Mobile"),
      holdSeconds: 6,
      repNames: ["Chris", "Ana"],
      requires: ["pin"],
      offers: [{ monthly: 70, months: 24, description: "Essentials plan at $70 for two lines", unlock: "ask" }],
      saveAttempts: 1,
      refundRate: 1,
    },
  },
  {
    id: "siriusxm",
    name: "SiriusXM",
    category: "streaming",
    phone: "+18666352349",
    hours: "8am to 10pm ET",
    verification: ["Radio ID or account number", "Account holder name", "Address on file"],
    ivr: ["Say 'cancel' to reach the retention team"],
    tactics: ["SiriusXM almost always offers a promo rate when you say you want to cancel", "Ask for the $5 to $6 a month rate for 12 months", "Confirm the price with fees included"],
    competitors: [{ name: "Spotify Premium", offer: "$11.99 a month" }],
    cancel: "Phone or online chat; ask for a cancellation confirmation number",
    typicalWin: "Down to about $5 to $8 a month for 12 months",
    sim: {
      menu: {
        prompt: "Welcome to SiriusXM. Please tell me the reason for your call. For example, you can say 'make a payment' or 'cancel my subscription'.",
        speech: true,
        options: [
          { digit: "1", label: "make a payment" },
          { digit: "2", label: "cancel my subscription", next: "retention" },
          { digit: "3", label: "billing", next: "billing" },
        ],
      },
      holdSeconds: 6,
      repNames: ["Gloria", "Sam"],
      requires: [],
      offers: [
        { monthly: 12, months: 12, description: "Music and entertainment for $12 a month for 12 months", unlock: "cancel" },
        { monthly: 6, months: 12, description: "$6 a month for 12 months plus fees", unlock: "loyalty" },
      ],
      saveAttempts: 2,
      refundRate: 1,
    },
  },
  {
    id: "planetfitness",
    name: "Planet Fitness",
    category: "gym",
    phone: "",
    hours: "Club hours",
    verification: ["Member name", "Home club", "Key tag or member number"],
    ivr: ["Call your home club directly; there is no central cancel line"],
    tactics: [
      "Many clubs now allow online cancellation; check first",
      "If the club insists on in-person or certified mail, ask for that in writing and send a letter",
      "Ask whether the annual fee has been billed and request a refund if it was charged after cancelling",
    ],
    competitors: [],
    cancel: "Online in the app where supported, in person, or certified letter to the home club",
    written: {},
    typicalWin: "Membership cancelled with no further charges",
    sim: {
      menu: { prompt: "Thanks for calling Planet Fitness. Press 1 for club hours. Press 2 to speak with a team member.", options: [{ digit: "1", label: "hours" }, { digit: "2", label: "team member", next: "cancel" }] },
      holdSeconds: 4,
      repNames: ["Kayla"],
      requires: ["dob"],
      offers: [{ monthly: 0, months: 3, description: "freeze the membership for three months at no charge", unlock: "cancel" }],
      saveAttempts: 1,
      refundRate: 1,
    },
  },
  {
    id: "nytimes",
    name: "The New York Times",
    category: "news",
    phone: "+18006984637",
    hours: "7am to 10pm ET weekdays, 7am to 3pm weekends",
    verification: ["Email on the account", "Account holder name"],
    ivr: ["Ask for subscription changes; cancellation is handled by the same team"],
    tactics: ["Ask for the introductory rate again; they usually offer $4 to $8 a month", "If not, cancel and ask for a confirmation email"],
    competitors: [],
    cancel: "Phone or online chat",
    typicalWin: "Back to about $4 a month for a year",
    sim: {
      menu: { prompt: "Thank you for calling The New York Times. For delivery issues press 1. For billing or to change your subscription press 2.", options: [{ digit: "1", label: "delivery" }, { digit: "2", label: "subscription changes", next: "retention" }] },
      holdSeconds: 6,
      repNames: ["Ellen"],
      requires: [],
      offers: [
        { monthly: 8, months: 12, description: "All Access at $8 a month for 12 months", unlock: "cancel" },
        { monthly: 4, months: 12, description: "$4 a month for one year", unlock: "loyalty" },
      ],
      saveAttempts: 2,
      refundRate: 1,
    },
  },
  {
    id: "adobe",
    name: "Adobe",
    category: "software",
    phone: "+18008336687",
    hours: "24/7 chat; phone 5am to 7pm PT",
    verification: ["Adobe ID email", "Account holder name"],
    ivr: ["Ask for 'cancel plan' to reach the retention team"],
    tactics: ["Annual plans billed monthly carry an early termination fee of 50% of the remaining months; ask for it to be waived", "Ask for two to three free months instead of cancelling"],
    competitors: [{ name: "Affinity", offer: "free for personal use since 2025" }],
    cancel: "Online in the account page or through chat",
    typicalWin: "Early termination fee waived or two free months",
    sim: {
      menu: { prompt: "Thank you for calling Adobe. For sales press 1. For help with an existing plan press 2.", options: [{ digit: "1", label: "sales" }, { digit: "2", label: "existing plan", next: "retention" }] },
      holdSeconds: 8,
      repNames: ["Ravi"],
      requires: [],
      offers: [
        { monthly: 0, months: 2, description: "two months free on your current plan", unlock: "cancel" },
        { monthly: 0, months: 0, description: "cancel with the early termination fee waived", unlock: "supervisor" },
      ],
      saveAttempts: 1,
      refundRate: 1,
    },
  },
];

export const GENERIC_MERCHANT: Merchant = {
  id: "other",
  name: "Other company",
  category: "other",
  phone: "",
  hours: "",
  verification: ["Account holder name", "Account number"],
  ivr: ["Choose billing or cancellation options; if asked, say the reason in a few words"],
  tactics: ["Be polite and specific about the number you want", "Ask what promotions the account qualifies for", "Ask for a supervisor if the first rep can't help"],
  competitors: [],
  cancel: "Ask for a cancellation confirmation number",
  typicalWin: "Varies",
  sim: {
    menu: cableMenu("our company"),
    holdSeconds: 8,
    repNames: ["Alex"],
    requires: [],
    offers: [{ monthly: 0, months: 0, description: "a one-time courtesy credit", unlock: "ask" }],
    saveAttempts: 1,
    refundRate: 1,
  },
};
